spring:
  profiles:
    active: development
---
spring:
  profiles: development
  application:
    name: edge-service
    
server:
  port: 8080
  
security:
  oauth2:
    resource:
      userInfoUri: http://user-service:8091/auth/user
  ignored: /catalog/**

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

zuul:
  ignored-services: '*'
  prefix:  /api
  routes:
    user-service: /user-service/**
  debug:
    request: true

user-service:
  ribbon:
    listOfServers: http://user-service:8091

ribbon.eureka.enabled: false

endpoints.routes.sensitive: false

---
spring:
  profiles: docker
  application:
    name: edge-service
    
server:
  port: 8080

security:
  oauth2:
    resource:
      userInfoUri: http://user-service:8091/auth/user
  ignored: /catalog/**

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

zuul:
  prefix:  /api
  routes:
    user-service: /user-service/**
  debug:
    request: true
    
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
  
endpoints.routes.sensitive: false