message: "I'm a config file from git repository."

spring:
  
  datasource:
    url: jdbc:mysql://${DOCKER_MACHINE_IP:mysqlserver}:3306/user_service
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    org.aitesting.microservices: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://${DOCKER_MACHINE_IP:discoveryservice}:8761/eureka/

server:
  contextPath:   /auth
  port: ${APP_PORT:8080}
  
security.oauth2.resource.filter-order: 3

axon:
  cluster-name: ${spring.application.name}

signing.key: “front-end-signing-key”