# Mongo config
spring:
  application:
    name: customerquery
  data:
    mongodb:
      database: ${spring.application.name}
      host: localhost
      port: 27017
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8080

amqp:
  events:
    host: localhost
    exchange-name: eventBus-customer
    queue-name: eventQueue-customer
    handlers: com.ultimatesoftware.banking.customer.query.domain.eventhandlers

endpoints:
  health:
    sensitive:  false

management:
  security:
    enabled: false
